<a href="https://colab.research.google.com/github/nguyenduychinh/AI_24_02_23/blob/main/AI_24_3_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
model.score(x,y)
x1=[[-0.5,-0.5],[1,-2],[-1,0.8],[3,5],[1,0.2],[-0.1,0.5]]
y1=model.predict(x1)
model.score(x1,y1)

1.0

In [ ]:
from sklearn.linear_model import Perceptron
x1=[[-0.5,-0.5],[1,-2],[-1,0.8],[3,5],[1,0.2],[-0.1,0.5]]
y1=model.predict(x1)
model=Perceptron()
model.fit(x1,y1)
model.score(x1,y1)

1.0

In [ ]:
x2=[[0.5,0]]
y2=model.predict(x2)
model.score(x2,y2)

1.0

In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
iris = datasets.load_iris()
x=iris.data
y=iris.target
print(x[:5])
print(y[:5])
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_train_std=sc.transform(x_test)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
model=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model.fit(x_train_std,y_train)
y_pred=model.predict(x_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình',accuracy_score(y_test,y_pred))

ValueError: ignored

In [ ]:
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd 
import numpy as np


url ='crabs.csv'
data = pd.read_csv(url)
data.head()

speies sex  index  fontallip  rearwidth  length  width  depth
0      B   M      1        8.1        6.7    16.1   19.0    7.0
1      B   M      2        8.8        7.7    18.1   20.8    7.4
2      B   M      3        9.2        7.8    19.0   22.4    7.7
3      B   M      4        9.6        7.9    20.1   23.1    8.2
4      B   M      5        9.8        8.0    20.3   23.0    8.2

In [ ]:
data_replace_1=data['speies'].replace(["B"], ["0"]).head(150)
data_replace_2=data['speies'].replace(["O"], ["1"]).head(150)
data_replace_3=data['sex'].replace(["M"], ["1"]).head(150)
data_replace_4=data['sex'].replace(["F"], ["0"]).head(150)



0      M
1      M
2      M
3      M
4      M
      ..
145    M
146    M
147    M
148    M
149    M
Name: sex, Length: 150, dtype: object

In [ ]:
from sklearn  import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split #tỉ lệ train_test là 7/3 hoặc 8/2. ko đc lấy train đi kiểm tra
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler #tỉ lệ các giá trị bằng nhau
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
iris=datasets.load_iris()
X=iris.data
y=iris.target
print(X[:5])
print(y[:5])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
sc=StandardScaler()
sc.fit(X_train)
X_train_Std=sc.transform(X_train)
X_test_Std=sc.transform(X_test)
model=Perceptron(max_iter=40, eta0=0.1,random_state=0)#tốc độ eta càng lớn thì sai càng nhiều, thấp thì hội tụ càng chập
model.fit(X_train_Std, y_train)
y_pred=model.predict(X_test_Std)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình: ',accuracy_score(y_test,y_pred))


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[0 0 2 2 1 1 2 2 0 0 0 0 2 2 0 2 1 1 2 2 2 0 0 2 0 1 2 2 2 0 0 1 0 0 2 0 1
 0 0 2 1 2 0 1 1]
[0 0 2 2 1 1 2 2 0 0 0 0 2 2 0 2 1 1 2 2 2 0 0 1 0 1 2 2 2 0 0 1 1 0 2 0 1
 0 0 2 1 2 1 1 2]
Độ chính xác của mô hình:  0.9111111111111111
